# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: security/v1beta1/request_authentication.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from type.v1beta1 import selector_pb2 as type_dot_v1beta1_dot_selector__pb2
from security.v1beta1 import jwt_pb2 as security_dot_v1beta1_dot_jwt__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='security/v1beta1/request_authentication.proto',
  package='istio.security.v1beta1',
  syntax='proto3',
  serialized_options=_b('Z\035istio.io/api/security/v1beta1'),
  serialized_pb=_b('\n-security/v1beta1/request_authentication.proto\x12\x16istio.security.v1beta1\x1a\x1btype/v1beta1/selector.proto\x1a\x1asecurity/v1beta1/jwt.proto\"\xc4\x01\n\x15RequestAuthentication\x12\x36\n\x08selector\x18\x01 \x01(\x0b\x32$.istio.type.v1beta1.WorkloadSelector\x12\x41\n\x05rules\x18\x02 \x03(\x0b\x32\x32.istio.security.v1beta1.RequestAuthentication.Rule\x1a\x30\n\x04Rule\x12(\n\x03jwt\x18\x01 \x01(\x0b\x32\x1b.istio.security.v1beta1.JWTB\x1fZ\x1distio.io/api/security/v1beta1b\x06proto3')
  ,
  dependencies=[type_dot_v1beta1_dot_selector__pb2.DESCRIPTOR,security_dot_v1beta1_dot_jwt__pb2.DESCRIPTOR,])




_REQUESTAUTHENTICATION_RULE = _descriptor.Descriptor(
  name='Rule',
  full_name='istio.security.v1beta1.RequestAuthentication.Rule',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='jwt', full_name='istio.security.v1beta1.RequestAuthentication.Rule.jwt', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=279,
  serialized_end=327,
)

_REQUESTAUTHENTICATION = _descriptor.Descriptor(
  name='RequestAuthentication',
  full_name='istio.security.v1beta1.RequestAuthentication',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='selector', full_name='istio.security.v1beta1.RequestAuthentication.selector', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rules', full_name='istio.security.v1beta1.RequestAuthentication.rules', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_REQUESTAUTHENTICATION_RULE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=327,
)

_REQUESTAUTHENTICATION_RULE.fields_by_name['jwt'].message_type = security_dot_v1beta1_dot_jwt__pb2._JWT
_REQUESTAUTHENTICATION_RULE.containing_type = _REQUESTAUTHENTICATION
_REQUESTAUTHENTICATION.fields_by_name['selector'].message_type = type_dot_v1beta1_dot_selector__pb2._WORKLOADSELECTOR
_REQUESTAUTHENTICATION.fields_by_name['rules'].message_type = _REQUESTAUTHENTICATION_RULE
DESCRIPTOR.message_types_by_name['RequestAuthentication'] = _REQUESTAUTHENTICATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestAuthentication = _reflection.GeneratedProtocolMessageType('RequestAuthentication', (_message.Message,), {

  'Rule' : _reflection.GeneratedProtocolMessageType('Rule', (_message.Message,), {
    'DESCRIPTOR' : _REQUESTAUTHENTICATION_RULE,
    '__module__' : 'security.v1beta1.request_authentication_pb2'
    # @@protoc_insertion_point(class_scope:istio.security.v1beta1.RequestAuthentication.Rule)
    })
  ,
  'DESCRIPTOR' : _REQUESTAUTHENTICATION,
  '__module__' : 'security.v1beta1.request_authentication_pb2'
  # @@protoc_insertion_point(class_scope:istio.security.v1beta1.RequestAuthentication)
  })
_sym_db.RegisterMessage(RequestAuthentication)
_sym_db.RegisterMessage(RequestAuthentication.Rule)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
